<a href="https://colab.research.google.com/github/Skshivu07/Titanic_dataset/blob/main/Copy_of_DataWrangling_Ajipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# ceate a dataframe for university as dataset
students=pd.DataFrame({
    "Student_ID":["S101","S102","S103","S104","S105","S106"],
    "Name":["Anuj","Ravi","Priya","Arun","Kamal","Meena"],
    "Department":["CSE","CSE","DS","DS","CSE","DS"],
    "Semester":[3,3,3,2,2,3]
})
students

  Student_ID   Name Department  Semester
0       S101   Anuj        CSE         3
1       S102   Ravi        CSE         3
2       S103  Priya         DS         3
3       S104   Arun         DS         2
4       S105  Kamal        CSE         2
5       S106  Meena         DS         3

In [ ]:
#create Multiple index
student_indexed=students.set_index(["Department","Semester","Student_ID"])
print(student_indexed)

                                 Name
Department Semester Student_ID
CSE        3        S101         Anuj
                    S102         Ravi
DS         3        S103        Priya
           2        S104         Arun
CSE        2        S105        Kamal
DS         3        S106        Meena

In [ ]:
df=students.set_index(["Department","Student_ID"])
print(df)

                        Name  Semester
Department Student_ID
CSE        S101         Anuj         3
           S102         Ravi         3
DS         S103        Priya         3
           S104         Arun         2
CSE        S105        Kamal         2
DS         S106        Meena         3

In [ ]:
# retrieve only CSE department
student_indexed.loc["CSE"]

                      Name
Semester Student_ID
3        S101         Anuj
         S102         Ravi
2        S105        Kamal

In [ ]:
#swaplevel - change the order of the index
student_indexed.swaplevel("Department","Semester")

                                 Name
Semester Department Student_ID
3        CSE        S101         Anuj
                    S102         Ravi
         DS         S103        Priya
2        DS         S104         Arun
         CSE        S105        Kamal
3        DS         S106        Meena

In [ ]:
# create a multiple index
temp=students.set_index(["Department","Student_ID"])
#swap
temp.swaplevel("Department","Student_ID")
# sorting
temp

                        Name  Semester
Department Student_ID
CSE        S101         Anuj         3
           S102         Ravi         3
DS         S103        Priya         3
           S104         Arun         2
CSE        S105        Kamal         2
DS         S106        Meena         3

In [ ]:
#sorting
temp.swaplevel("Department","Student_ID").sort_index()

                        Name  Semester
Student_ID Department
S101       CSE          Anuj         3
S102       CSE          Ravi         3
S103       DS          Priya         3
S104       DS           Arun         2
S105       CSE         Kamal         2
S106       DS          Meena         3

In [ ]:
marks=pd.DataFrame({
    "Internal":[82,75,94,80,68,85],
    "Final":[88,72,94,80,70,89]
},index=pd.MultiIndex.from_tuples([
    ("CSE","S101"),
    ("CSE","S102"),
    ("DS","S103"),
    ("DS","S104"),
    ("CSE","S105"),
    ("DS","S106")],
    names=["Department","Student_ID"]))
marks

                       Internal  Final
Department Student_ID
CSE        S101              82     88
           S102              75     72
DS         S103              94     94
           S104              80     80
CSE        S105              68     70
DS         S106              85     89

In [ ]:
#calculating the departmental wise total
marks.groupby(level="Department").mean()

             Internal      Final
Department
CSE         75.000000  76.666667
DS          86.333333  87.666667

In [ ]:
#combining and Mergimg Dataset
#merge
#concat

In [ ]:
#create 2 table - Student Table
Student_info=pd.DataFrame({
    "Student_ID":["S101","S102","S103","S104"],
    "Name":["Anish","Riya","Manish kumar","Janvi"],
    "Department":["CSE","CSE","DS","DS"]
})
print(Student_info)

  Student_ID          Name Department
0       S101         Anish        CSE
1       S102          Riya        CSE
2       S103  Manish kumar         DS
3       S104         Janvi         DS

In [ ]:
# 2. Examination Table
exam = pd.DataFrame({
    "Student_ID":["S101","S102","S103","S105"],
    "Internal":[82,75,90,68],
    "Final":[88,72,94,70]
})
print(exam)

  Student_ID  Internal  Final
0       S101        82     88
1       S102        75     72
2       S103        90     94
3       S105        68     70

In [ ]:
#Merge - default - inner join
result=pd.merge(Student_info,exam,on="Student_ID",how="inner")
print(result)

  Student_ID          Name Department  Internal  Final
0       S101         Anish        CSE        82     88
1       S102          Riya        CSE        75     72
2       S103  Manish kumar         DS        90     94

In [ ]:
# Left join
Leftjoin_result=pd.merge(Student_info,exam,on="Student_ID",how="left")
print(Leftjoin_result)

  Student_ID          Name Department  Internal  Final
0       S101         Anish        CSE      82.0   88.0
1       S102          Riya        CSE      75.0   72.0
2       S103  Manish kumar         DS      90.0   94.0
3       S104         Janvi         DS       NaN    NaN

In [ ]:
#Right_join
Rightjoin_result=pd.merge(Student_info,exam,on="Student_ID",how="right")
print(Rightjoin_result)

  Student_ID          Name Department  Internal  Final
0       S101         Anish        CSE        82     88
1       S102          Riya        CSE        75     72
2       S103  Manish kumar         DS        90     94
3       S105           NaN        NaN        68     70

In [ ]:
# outerjoin
outerjoin_result=pd.merge(Student_info,exam,on="Student_ID",how="outer")
print(outerjoin_result)

  Student_ID          Name Department  Internal  Final
0       S101         Anish        CSE      82.0   88.0
1       S102          Riya        CSE      75.0   72.0
2       S103  Manish kumar         DS      90.0   94.0
3       S104         Janvi         DS       NaN    NaN
4       S105           NaN        NaN      68.0   70.0

In [ ]:
# Inner join - only command record (intersection)
# outer join - everything from both(union)
# left join - everything in the left + matchimg right
# right join - everything in the right + matching left

In [ ]:
# create 2 files
S_info=pd.DataFrame({
    "Student_ID":["S101","S102","S103","S104"],
    "Name":["Anish","Riya","Manish kumar","Janvi"],
    "Department":["CSE","CSE","DS","DS"]
})
exam1=pd.DataFrame({
    "ID":["S101","S102","S103"],
    "Marks":[88,72,95]
})

#merge 2 file - but no common column present in this
pd.merge(S_info,exam1,left_on="Student_ID",right_on="ID")

  Student_ID          Name Department    ID  Marks
0       S101         Anish        CSE  S101     88
1       S102          Riya        CSE  S102     72
2       S103  Manish kumar         DS  S103     95