<a href="https://colab.research.google.com/github/Skshivu07/Titanic_dataset/blob/main/data__transform.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Data Strucrure
# Handle Missing Values
# Data Transformation
# String Manipulation

In [1]:
import numpy as np
import pandas as pd

In [17]:
# Create your own dataset
data={'Student_ID':[101,102,103,104,105,106,107,108,109,110,111,112],
      'Name':['Rahul Kumar','amit sharma','PRIYA SINGH','Neha Verma','Ravi kumar','anjali gupta','vikas singh','POOJA SHARMA','Karan Mehta','sneha kumari','Arjun singh','Riya Verma'],
      'Gender':['Male','Male','Female','Female','Male','Female','Male','Female','Male','Female','Male','Female'],
      'Department':['CSE','CSE','ECE','CSE','ECE','CSE','ME','CSE','ECE','ME','CSE','ECE'],
      'Age':[20,21,np.nan,22,21,20,23,np.nan,22,21,20,22],
      'Attendance':[85,78,90,np.nan,75,88,65,92,np.nan,70,95,80],
      'Marks':[85,72,np.nan,91,68,88,55,np.nan,76,64,95,81],
      'Email':['rahul@gmail.com','amit@gmail.com','priya@gmail.com','neha@gmail.com','None','anjali@gmail.com','vikas@gmail.com','pooja@gmail.com','None','None','None','None'],
}
df=pd.DataFrame(data)
display(df)

,Student_ID,Name,Gender,Department,Age,Attendance,Marks,Email
0,101,Rahul Kumar,Male,CSE,20.0,85.0,85.0,rahul@gmail.com
1,102,amit sharma,Male,CSE,21.0,78.0,72.0,amit@gmail.com
2,103,PRIYA SINGH,Female,ECE,NaN,90.0,NaN,priya@gmail.com
3,104,Neha Verma,Female,CSE,22.0,NaN,91.0,neha@gmail.com
4,105,Ravi kumar,Male,ECE,21.0,75.0,68.0,None
5,106,anjali gupta,Female,CSE,20.0,88.0,88.0,anjali@gmail.com
6,107,vikas singh,Male,ME,23.0,65.0,55.0,vikas@gmail.com
7,108,POOJA SHARMA,Female,CSE,NaN,92.0,NaN,pooja@gmail.com
8,109,Karan Mehta,Male,ECE,22.0,NaN,76.0,None
9,110,sneha kumari,Female,ME,21.0,70.0,64.0,None
10,111,Arjun singh,Male,CSE,20.0,95.0,95.0,None
11,112,Riya Verma,Female,ECE,22.0,80.0,81.0,None

In [18]:
print('shape:',df.shape)
print('Columns:',df.columns.tolist)
display(df.head())
display(df.tail())

shape: (12, 8)
Columns: <bound method IndexOpsMixin.tolist of Index(['Student_ID', 'Name', 'Gender', 'Department', 'Age', 'Attendance',
       'Marks', 'Email'],
      dtype='object')>

,Student_ID,Name,Gender,Department,Age,Attendance,Marks,Email
0,101,Rahul Kumar,Male,CSE,20.0,85.0,85.0,rahul@gmail.com
1,102,amit sharma,Male,CSE,21.0,78.0,72.0,amit@gmail.com
2,103,PRIYA SINGH,Female,ECE,NaN,90.0,NaN,priya@gmail.com
3,104,Neha Verma,Female,CSE,22.0,NaN,91.0,neha@gmail.com
4,105,Ravi kumar,Male,ECE,21.0,75.0,68.0,None

,Student_ID,Name,Gender,Department,Age,Attendance,Marks,Email
7,108,POOJA SHARMA,Female,CSE,NaN,92.0,NaN,pooja@gmail.com
8,109,Karan Mehta,Male,ECE,22.0,NaN,76.0,None
9,110,sneha kumari,Female,ME,21.0,70.0,64.0,None
10,111,Arjun singh,Male,CSE,20.0,95.0,95.0,None
11,112,Riya Verma,Female,ECE,22.0,80.0,81.0,None

In [21]:
# Detect Missing Values
print(df.isnull().sum())

Student_ID    0
Name          0
Gender        0
Department    0
Age           2
Attendance    2
Marks         2
Email         0
dtype: int64

In [22]:
#Handle the missing values
df['Age']=df['Age'].fillna(df['Age'].mean())
df['Attendance']=df['Attendance'].fillna(df['Attendance'].median())
df['Marks']=df['Marks'].fillna(df['Marks'].mean())
df['Email']=df['Email'].fillna('Not Provided')
print(df.isnull().sum())

Student_ID    0
Name          0
Gender        0
Department    0
Age           0
Attendance    0
Marks         0
Email         0
dtype: int64

In [ ]:
#data Transformation
df['Result']=df['Marks'].apply(lambda x:'Pass' if x>=40 else 'Fail')

def assign_grade(marks)
 if marks>=80:return 'A'
 elif marks>=80:return 'B'