<a href="https://colab.research.google.com/github/Skshivu07/Titanic_dataset/blob/main/dsv_iris_file_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Loading Storage and file formats
1. load the data from local file
2. load the data from outside also
3. file format - csv, Excel,json,parquet store this load the file
    display the content in file

In [2]:
import pandas as pd

In [3]:
raw_data={
    "Name":["Amit","Riya","Priya","Karan","Rahul"],
    "Age":[20,21,20,21,22],
    "Departement":["CSE","IT","ECE","CSE","IT"],
    "Marks":[85,90,78,88,76]
}
df=pd.DataFrame(raw_data)
df

    Name  Age Departement  Marks
0   Amit   20         CSE     85
1   Riya   21          IT     90
2  Priya   20         ECE     78
3  Karan   21         CSE     88
4  Rahul   22          IT     76

# add 5 more row in the existing dataframe
1. convert to different file format
2. compare the file size

In [12]:
# inspect dataFrame
print("Shape(rows, columns):",df.shape)
print(df.head(3))
print(df.tail(2))
print(df.columns)
print(df.columns.tolist())
print(df.dtypes)
print(df.describe())
print(df.info())

Shape(rows, columns): (5, 4)
    Name  Age Departement  Marks
0   Amit   20         CSE     85
1   Riya   21          IT     90
2  Priya   20         ECE     78
    Name  Age Departement  Marks
3  Karan   21         CSE     88
4  Rahul   22          IT     76
Index(['Name', 'Age', 'Departement', 'Marks'], dtype='object')
['Name', 'Age', 'Departement', 'Marks']
Name           object
Age             int64
Departement    object
Marks           int64
dtype: object
            Age     Marks
count   5.00000   5.00000
mean   20.80000  83.40000
std     0.83666   6.14817
min    20.00000  76.00000
25%    20.00000  78.00000
50%    21.00000  85.00000
75%    21.00000  88.00000
max    22.00000  90.00000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         5 non-null      object
 1   Age          5 non-null      int64
 2   Departement  5 non-null      object
 3   Marks        5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes
None

In [13]:
iris=pd.read_csv("/content/Iris.csv")
iris.head(3)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa

In [14]:
print(iris.shape)
print(iris.columns.tolist())
print(iris.info())

(150, 6)
['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB
None

In [18]:
# file formats
iris.to_csv("iris_csvoutput.csv",index=False)

# load
iris_csv=pd.read_csv("/content/iris_csvoutput.csv")
iris_csv.head(7)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa

In [20]:
iris.to_excel("iris_exceloutput.xlsx",index=False)
#load
iris_excel=pd.read_excel("/content/iris_exceloutput.xlsx")
iris_excel.tail(8)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
142,143,5.8,2.7,5.1,1.9,Iris-virginica
143,144,6.8,3.2,5.9,2.3,Iris-virginica
144,145,6.7,3.3,5.7,2.5,Iris-virginica
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [21]:
iris.to_json("iris_joutput.json",
             orient="records",
             indent=4)
# load and execute it
iris_json=pd.read_json("/content/iris_joutput.json")
iris_json.head(6)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa

In [22]:
iris.to_parquet("iris_paroutput.parquet",index=False)
#loasd and display
iris_parquet=pd.read_parquet("/content/iris_paroutput.parquet")
iris_parquet.head(6)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa

In [23]:
import os
files=[
    "iris_csvoutput.csv",
    "iris_exceloutput.xlsx",
    "iris_joutput.json",
    "iris_paroutput.parquet"
]
for file in files:
  size=os.path.getsize(file)
  print(f"{file}:{size} bytes")

iris_csvoutput.csv:5107 bytes
iris_exceloutput.xlsx:9208 bytes
iris_joutput.json:26794 bytes
iris_paroutput.parquet:5932 bytes

In [24]:
#load tghe selected columns

iris_selected_col=pd.read_csv("/content/Iris.csv",
                              usecols=["SepalWidthCm","SepalLengthCm", "PetalWidthCm"])
iris_selected_col.head()

   SepalLengthCm  SepalWidthCm  PetalWidthCm
0            5.1           3.5           0.2
1            4.9           3.0           0.2
2            4.7           3.2           0.2
3            4.6           3.1           0.2
4            5.0           3.6           0.2